version: '3'
services:
  nginx:
    ports:
      - '80:80'

  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_USER=mongo
      - MONGO_PASSWORD=mongo
    command: npm run start

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
